[2024-11-16T04:27:00.260+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-16T04:27:00.379+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_news_crawler.fetch_news_data scheduled__2024-11-15T00:00:00+00:00 [queued]>
[2024-11-16T04:27:00.444+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_news_crawler.fetch_news_data scheduled__2024-11-15T00:00:00+00:00 [queued]>
[2024-11-16T04:27:00.463+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-16T04:27:00.658+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_news_data> on 2024-11-15 00:00:00+00:00
[2024-11-16T04:27:00.821+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=74) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-16T04:27:00.872+0000] {standard_task_runner.py:72} INFO - Started process 83 to run task
[2024-11-16T04:27:00.855+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_news_crawler', 'fetch_news_data', 'scheduled__2024-11-15T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/nh_news_crawling.py', '--cfg-path', '/tmp/tmpas_v2wlf']
[2024-11-16T04:27:00.971+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask fetch_news_data
[2024-11-16T04:27:01.695+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_news_crawler.fetch_news_data scheduled__2024-11-15T00:00:00+00:00 [running]> on host 25eebfd415ad
[2024-11-16T04:27:02.127+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_news_crawler' AIRFLOW_CTX_TASK_ID='fetch_news_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-15T00:00:00+00:00'
[2024-11-16T04:27:02.131+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-16T04:27:02.133+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-16T04:27:02.137+0000] {logging_mixin.py:190} INFO - Current task name:fetch_news_data state:running start_date:2024-11-16 04:27:00.381812+00:00
[2024-11-16T04:27:02.140+0000] {logging_mixin.py:190} INFO - Dag name:daily_news_crawler and current dag run status:running
[2024-11-16T04:27:02.147+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-16T04:27:10.848+0000] {logging_mixin.py:190} INFO - Error saving to database: ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Cannot open server 'jy-nh-server01' requested by the login. Client with IP address '210.94.220.229' is not allowed to access the server.  To enable access, use the Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect. (40615) (SQLDriverConnect)")
[2024-11-16T04:27:10.860+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-16T04:27:10.939+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-16T04:27:10.957+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=daily_news_crawler, task_id=fetch_news_data, run_id=scheduled__2024-11-15T00:00:00+00:00, execution_date=20241115T000000, start_date=20241116T042700, end_date=20241116T042710
[2024-11-16T04:27:11.085+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-16T04:27:11.102+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-16T04:27:11.120+0000] {logging_mixin.py:190} INFO - Dag name:daily_news_crawler queued_at:2024-11-16 04:26:16.560238+00:00
[2024-11-16T04:27:11.136+0000] {logging_mixin.py:190} INFO - Task hostname:25eebfd415ad operator:PythonOperator
[2024-11-16T04:27:11.400+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-16T04:27:11.521+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-16T04:27:11.542+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
